### ISSUE TITLE
functional refactor

### ISSUE THREAD

**Issue by 0thernet** [benzguo/MusicKit#2]
Chords should be functions 
Chord :: Pitch -> PitchSet
Chord.Major(c4)

Scales should be polymorphic functions
Scale.Minor(c4)
Scale.Minor([1, 3, 5]) (c4)

PitchSet should support operators:
PitchSet +/- PitchSet
PitchSet +/- Float

**Comment by benzguo** [comment]
add https://github.com/thoughtbot/Runes and use flatMap
