### ISSUE TITLE
Is it support for IOS?

### ISSUE THREAD

**Issue by etamity** [benzguo/MusicKit#31]
I have tried to build it with IOS target, but always not found the MusicKit ?

**Comment by etamity** [comment]
I have tried to run it on IOS, and both Mac and IPhone, didn't hear MIDI sound output ?

**Comment by 0thernet** [comment]
I haven't created an iOS example yet, but the examples do work on a Mac. The example apps transform MIDI, but do not produce sound. If you have a MIDI keyboard, the ChordRecognition example will identify the chords you play.

Creating more intuitive examples with audio output is definitely on the roadmap, but I've been pretty busy lately.
