### ISSUE TITLE
iOS keyboard

### ISSUE THREAD

**Issue by 0thernet** [benzguo/MusicKit#35]
- scrollable (bottom/top scrollbar)
- stretchable (within octaves)
- xy vibrato-able
- force-touchable

https://medium.com/@rknla/exploring-apple-s-3d-touch-f5980ef45af5

**Comment by aure** [comment]
Sounds awesome.  I want this to happen.

**Comment by 0thernet** [comment]
Feeling less motivated to finish this now that this app exists: https://itunes.apple.com/us/app/noise/id1011132019?mt=8

**Comment by aure** [comment]
And that keyboard's source code is available for everyone to use in their own projects?
