### ISSUE TITLE
how to play a midi with Chord ..

### ISSUE THREAD

**Issue by laidingqing** [benzguo/MusicKit#36]
the chaosHarmonizer example don't run everything..

``` swift
let midi = MIDI(name: "ChaosHarmonizer")
        midi.noteHandler = { messages in
            if let first = messages.first {
                if first.on {
                    let possibleChords = [
                        ChordQuality.Major,
                        ChordQuality.Minor,
                        ChordQuality.Sus2,
                        ChordQuality.Sus4,
                    ]

'''
```

**Comment by 0thernet** [comment]
The example isn't well documented – to use it, you'll need:
- a MIDI keyboard for MIDI input
- software that can receive MIDI input (e.g. a DAW like Ableton)

The harmonizer example takes MIDI input on one channel and outputs harmonized MIDI input on another channel.
